force-app/main/default/objects/Mizuho_Dashboard_State__c/Mizuho_Dashboard_State__c.object-meta.xml
<CustomObject>
    <label>Mizuho Dashboard State</label>
    <nameField>
        <label>Mizuho Dashboard State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mizuho Dashboard State</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mizuho_Dashboard_State__c/fields/DashboardState__c.field-meta.xml
<CustomField>
    <fullName>DashboardState__c</fullName>
    <label>Dashboard State</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Mizuho_Dashboard_State__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MizuhoDashboardStateController.cls
global with sharing class MizuhoDashboardStateController {

    @AuraEnabled
    global static Boolean saveState(String userId, String state) {
        
        Mizuho_Dashboard_State__c dashboardState = null;
        
        try {
            dashboardState = [SELECT Id,Name,DashboardState__c,UserId__c FROM Mizuho_Dashboard_State__c WHERE UserId__c =: userId];
        } catch (Exception e) {
        	dashboardState = new Mizuho_Dashboard_State__c();
        }
        
        dashboardState.DashboardState__c = state;
        dashboardState.UserId__c = userId;
        
        upsert dashboardState;
        
        return true;
    }
}