force-app/main/default/objects/Fortnite_Player__c/Fortnite_Player__c.object-meta.xml
<CustomObject>
    <description>Represents player data such as uid, username, stats, etc.</description>
    <label>Fortnite Player</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fortnite Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fortnite_Player__c/fields/platforms__c.field-meta.xml
<CustomField>
    <fullName>platforms__c</fullName>
    <description>The platforms that the player has used</description>
    <label>platforms</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Fortnite_Player__c/fields/seasons__c.field-meta.xml
<CustomField>
    <fullName>seasons__c</fullName>
    <description>The seasons that the player has played</description>
    <label>seasons</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Fortnite_Player__c/fields/uid__c.field-meta.xml
<CustomField>
    <fullName>uid__c</fullName>
    <description>Unique ID for the player</description>
    <externalId>true</externalId>
    <label>uid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fortnite_Player__c/fields/username__c.field-meta.xml
<CustomField>
    <fullName>username__c</fullName>
    <description>The unique userrname for the player</description>
    <externalId>true</externalId>
    <label>username</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Fortnite_Player_Stats__c/Fortnite_Player_Stats__c.object-meta.xml
<CustomObject>
    <label>Fortnite Player Stats</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fortnite Player Stats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fortnite_Player_Stats__c/fields/bestscore__c.field-meta.xml
<CustomField>
    <fullName>bestscore__c</fullName>
    <defaultValue>0</defaultValue>
    <label>bestscore</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fortnite_Player_Stats__c/fields/Fortnite_Player__c.field-meta.xml
<CustomField>
    <fullName>Fortnite_Player__c</fullName>
    <label>Fortnite Player</label>
    <referenceTo>Fortnite_Player__c</referenceTo>
    <relationshipLabel>stats</relationshipLabel>
    <relationshipName>Fortnite_Player_Stats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fortnite_Player_Stats__c/fields/gametype__c.field-meta.xml
<CustomField>
    <fullName>gametype__c</fullName>
    <description>The game type</description>
    <label>gametype</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>solo</fullName>
            </value>
            <value>
                <fullName>duo</fullName>
            </value>
            <value>
                <fullName>squad</fullName>
            </value>
            <value>
                <fullName>ltm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fortnite_Player_Stats__c/fields/input__c.field-meta.xml
<CustomField>
    <fullName>input__c</fullName>
    <description>The input type</description>
    <label>input</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>touch</fullName>
            </value>
            <value>
                <fullName>gamepad</fullName>
            </value>
            <value>
                <fullName>keyboardmouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fortnite_Player_Stats__c/fields/kd__c.field-meta.xml
<CustomField>
    <fullName>kd__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>kd</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fortnite_Player_Stats__c/fields/kills__c.field-meta.xml
<CustomField>
    <fullName>kills__c</fullName>
    <defaultValue>0</defaultValue>
    <label>kills</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fortnite_Player_Stats__c/fields/matchesplayed__c.field-meta.xml
<CustomField>
    <fullName>matchesplayed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>matchesplayed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fortnite_Player_Stats__c/fields/minutesplayed__c.field-meta.xml
<CustomField>
    <fullName>minutesplayed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>minutesplayed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fortnite_Player_Stats__c/fields/placetop10__c.field-meta.xml
<CustomField>
    <fullName>placetop10__c</fullName>
    <defaultValue>0</defaultValue>
    <label>placetop10</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fortnite_Player_Stats__c/fields/placetop12__c.field-meta.xml
<CustomField>
    <fullName>placetop12__c</fullName>
    <defaultValue>0</defaultValue>
    <label>placetop12</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fortnite_Player_Stats__c/fields/placetop1__c.field-meta.xml
<CustomField>
    <fullName>placetop1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>placetop1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fortnite_Player_Stats__c/fields/placetop25__c.field-meta.xml
<CustomField>
    <fullName>placetop25__c</fullName>
    <defaultValue>0</defaultValue>
    <label>placetop25</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fortnite_Player_Stats__c/fields/placetop3__c.field-meta.xml
<CustomField>
    <fullName>placetop3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>placetop3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fortnite_Player_Stats__c/fields/placetop5__c.field-meta.xml
<CustomField>
    <fullName>placetop5__c</fullName>
    <defaultValue>0</defaultValue>
    <label>placetop5</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fortnite_Player_Stats__c/fields/placetop6__c.field-meta.xml
<CustomField>
    <fullName>placetop6__c</fullName>
    <defaultValue>0</defaultValue>
    <label>placetop6</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fortnite_Player_Stats__c/fields/playersoutlived__c.field-meta.xml
<CustomField>
    <fullName>playersoutlived__c</fullName>
    <defaultValue>0</defaultValue>
    <label>playersoutlived</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fortnite_Player_Stats__c/fields/score__c.field-meta.xml
<CustomField>
    <fullName>score__c</fullName>
    <defaultValue>0</defaultValue>
    <label>score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fortnite_Player_Stats__c/fields/uid__c.field-meta.xml
<CustomField>
    <fullName>uid__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The generated unique ID based on the player&apos;s uid, gametype, season, and input</description>
    <externalId>true</externalId>
    <label>uid</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Fortnite_Player_Stats__c/fields/winrate__c.field-meta.xml
<CustomField>
    <fullName>winrate__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>winrate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FortniteAPIController2.cls
/* Class for use with the fornite Lightning Component */
global with sharing class FortniteAPIController2 {

    private static String FortniteApiKey = '6761864a-6d460da2-1081f57d-e2c14a6d';
    
    global class FortnitePlayer {
        public String username;
        public String account_id;        
    }
    
    global class FortniteStatDetails {
        public Integer placetop1 { get; set; }
        public Integer placetop3 { get; set; }
        public Integer placetop5 { get; set; }
        public Integer placetop6 { get; set; }
        public Integer placetop10 { get; set; }
        public Integer placetop12 { get; set; }
        public Integer placetop25 { get; set; }
        public Integer matchesplayed { get; set; }
        public Integer minutesplayed { get; set; }
        public Integer kills { get; set; }
        public Integer score { get; set; }
        public Integer bestscore { get; set; }
        public Integer playersoutlived { get; set; }
        public Double kd { get; set; }
        public Double winrate { get; set; }
    }
/*
    global class FortniteStatsByGameType {
        public FortniteStatDetails solo { get; set; }
        public FortniteStatDetails duo { get; set; }
        public FortniteStatDetails squad { get; set; }
        public FortniteStatDetails ltm { get; set; }
    }
    
    global class FortniteStatsByControllerType {
        public Map<String, FortniteStatDetails> touch { get; set; }
        public Map<String, FortniteStatDetails> gamepad { get; set; }
        public Map<String, FortniteStatDetails> keyboardmouse { get; set; }
    }
*/    
    global class FortniteAccountStats {
        public Integer level { get; set; }
        public Double progress_pct { get; set; }
    }
    
    global class FortniteStats {
        public Boolean result { get; set; }
        public String source { get; set; }
        public String mode { get; set; }
        public String name { get; set; }
        public FortniteAccountStats account { get; set; }
        public Map<String, FortniteStatDetails> global_stats { get; set; }
        public Map<String, Map<String, FortniteStatDetails>> per_input { get; set; }
        public List<Integer> seasons_available { get; set; }
        public String season { get; set; }
    }

    
    @AuraEnabled
    global static String getGlobalPlayerStats(String username, String season) {
        
        if (season == null || season == '') {
            season = 'all';
        }


        FortnitePlayer player = null;
        
        Fortnite_Player__c playerRecord = null;
        
        String uid = null;

        try {
            playerRecord = [SELECT Id, Name, uid__c, username__c, platforms__c, seasons__c, LastModifiedDate FROM Fortnite_Player__c WHERE username__c =: username];
            player = new FortnitePlayer();
            player.account_id = playerRecord.uid__c;
            player.username = playerRecord.username__c;
        } catch (Exception e) {
            System.debug('Exception: ' + e);
            //return '{"error":"Player with username ' + username + ' was not found. Please try using getPlayerInfo."}';
	        player = lookupPlayerByUsername(username);
            playerRecord = new Fortnite_Player__c();
            
            playerRecord.uid__c = player.account_id;
            playerRecord.username__c = player.username;
        }        
        
        System.debug('player: ' + player);
        System.debug('playerRecord: ' + playerRecord);
        
        List<Fortnite_Player__c> playerStatsRecords = null;
     
        try {
            playerStatsRecords = [SELECT Id,Name,uid__c,username__c,
                           			(SELECT Id,input__c,gametype__c,kills__c,kd__c,score__c,bestscore__c,matchesplayed__c,minutesplayed__c,placetop1__c,placetop3__c,placetop5__c,placetop6__c,placetop10__c,placetop25__c,playersoutlived__c,winrate__c
                            			FROM Fortnite_Player_Stats__r)
                           			FROM Fortnite_Player__c WHERE username__c =: playerRecord.username__c];
        } catch (Exception e) {
            System.debug('Exception: ' + e);
            playerStatsRecords = new List<Fortnite_Player__c>();            
        }
        
        System.debug('playerStatsRecords: ' + playerStatsRecords);        
        
        List<Fortnite_Player_Stats__c> playerStats = [SELECT Id,input__c,gametype__c,kills__c,kd__c,score__c,bestscore__c,matchesplayed__c,minutesplayed__c,placetop1__c,placetop3__c,placetop5__c,placetop6__c,placetop10__c,placetop25__c,playersoutlived__c,winrate__c
                            			FROM Fortnite_Player_Stats__c];

        System.debug('playerStats: ' + playerStats);        
        
        Map<String, Fortnite_Player_Stats__c> playerStatsMap = new Map<String, Fortnite_Player_Stats__c>();
        String key = null;
        for (Fortnite_Player_Stats__c stats: playerStats) {
            System.debug('stats: ' + stats);
            key = (stats.input__c == null) ? '' : stats.input__c;
            key += '_' + stats.gametype__c;
            System.debug('key: ' + key);
            playerStatsMap.put(key, stats);
            //System.debug('playerStatsRecord: ' + (Fortnite_Player_Stats__c) playerStatsRecord.Id);
            //key = (playerStatsRecord.input__c == null) ? 'global' : playerStatsRecord.input__c;
            //playerStatsRecordMap.put(key, playerStatsRecord);
        }
        
        String url = 'https://fortniteapi.io/stats?account=' + player.account_id + '&season=' + season;
        
        HttpRequest request = new HttpRequest();        
        Http http = new Http();
        request.setEndpoint(url);
        request.setMethod('GET');
        request.setHeader('Authorization', FortniteApiKey);
        
        HTTPResponse response = http.send(request);
        
        System.debug('response.body: ' + response.getBody());
    
        
       	upsert playerRecord;

        
        FortniteStats stats = (FortniteStats) JSON.deserialize(response.getBody(), FortniteStats.class);
        
        System.debug('stats: ' + stats);
        
        List<String> inputTypes = new List<String>{ 'touch', 'gamepad', 'keyboardmouse' };
        List<String> gameTypes = new List<String>{ 'solo', 'duo', 'squad', 'ltm' };
            
		FortniteStatDetails statDetails = null;
		Map<String, FortniteStatDetails> statDetailsMap = null;
        
        Fortnite_Player_Stats__c playerStatsRecord = null;
        
        for (String gameType: gameTypes) {
            System.debug('gameType: ' + gameType);
            statDetails = (FortniteStatDetails) stats.global_stats.get(gameType);
            System.debug('statDetails: ' + statDetails);
            if (statDetails != null) {
                playerStatsRecord = createFortnitePlayerStatsRecord(playerRecord, null, gameType, statDetails);
                System.debug('playerStatsRecord: ' + playerStatsRecord);
                
                upsert playerStatsRecord;
            }
        }

        for (String inputType: inputTypes) {
            System.debug('inputType: ' + inputType);
            statDetailsMap = (Map<String, FortniteStatDetails>) stats.per_input.get(inputType);
            if (statDetailsMap != null) {
                for (String gameType: gameTypes) {
                    System.debug('gameType: ' + gameType);
                    statDetails = (FortniteStatDetails) statDetailsMap.get(gameType);
                    System.debug('statDetails: ' + statDetails);
                    if (statDetails != null) {
                        playerStatsRecord = createFortnitePlayerStatsRecord(playerRecord, inputType, gameType, statDetails);
                        System.debug('playerStatsRecord: ' + playerStatsRecord);
                        
                        upsert playerStatsRecord;

                    }
                }
            }
        }
        
        /*       
        Boolean result;
        String source;
        String mode;
        String name;
        FortniteAccountStats account;
        FortniteStatsByGameType global_stats;
        FortniteStatsByControllerType per_input;
        List<Integer> seasons_available;
        String season;        
   */     

        
//        SELECT Id,Name,eadx__uid__c,eadx__username__c, (SELECT Id,eadx__kills__c FROM eadx__Fortnite_Player_Stats__r) FROM eadx__Fortnite_Player__c WHERE eadx__username__c = 'Bloxitect'             
//        
        // Note that second argument determines null suppression
        String statsJson = JSON.serialize(stats, true);
        System.debug('statsJson: ' + statsJson);
        
        return statsJson;
    }
    

    global static Fortnite_Player_Stats__c createFortnitePlayerStatsRecord(Fortnite_Player__c playerRecord, String input, String gametype, FortniteStatDetails details) {
        System.debug('updateFortnitePlayerStatsRecord: ' + playerRecord + ', ' + input + ', ' + gametype);
        System.debug('updateFortnitePlayerStatsRecord: ' + details);
        
        Fortnite_Player_Stats__c stats = new Fortnite_Player_Stats__c();
        
        stats.Fortnite_Player__c = playerRecord.Id;
        
        stats.input__c = input;
        stats.gametype__c = gametype;
        
        stats.winrate__c = details.winrate;
        stats.score__c = details.score;
        stats.playersoutlived__c = details.playersoutlived;
        stats.placetop1__c = details.placetop1;
        stats.placetop3__c = details.placetop3;
        stats.placetop5__c = details.placetop5;
        stats.placetop6__c = details.placetop6;
        stats.placetop10__c = details.placetop10;
        stats.placetop12__c = details.placetop12;
        stats.placetop25__c = details.placetop25;
        stats.minutesplayed__c = details.minutesplayed;
        stats.matchesplayed__c = details.matchesplayed;
        stats.kills__c = details.kills;
        stats.kd__c = details.kd;
        
        return stats;
        
    }
    
    @AuraEnabled
    global static String listGameModes(String lang) {
        
        if (lang == null || lang == '') {
            lang = 'en';
        }
        
        String url = 'https://fortniteapi.io/game/modes?lang=' + lang;
        
        HttpRequest request = new HttpRequest();        
        Http http = new Http();
        request.setEndpoint(url);
        request.setMethod('GET');
        request.setHeader('Authorization', FortniteApiKey);
        
        HTTPResponse response = http.send(request);
        
        System.debug('response.body: ' + response.getBody());
        
        return response.getBody();
    }

    @AuraEnabled
    global static String listSeasons() {
        
        String url = 'https://fortniteapi.io/seasons/list';
        
        HttpRequest request = new HttpRequest();        
        Http http = new Http();
        request.setEndpoint(url);
        request.setMethod('GET');
        request.setHeader('Authorization', FortniteApiKey);
        
        HTTPResponse response = http.send(request);
        
        System.debug('response.body: ' + response.getBody());
        
        return response.getBody();
    }
    
    
    @AuraEnabled
    global static String lookupAccountIdByUsername(String username) {
        
        String url = 'https://fortniteapi.io/lookup?username=' + username;
        
        HttpRequest request = new HttpRequest();        
        Http http = new Http();
        request.setEndpoint(url);
        request.setMethod('GET');
        request.setHeader('Authorization', FortniteApiKey);
        
        HTTPResponse response = http.send(request);
        
        System.debug('response.body: ' + response.getBody());
        
        FortnitePlayer player = (FortnitePlayer) JSON.deserialize(response.getBody(), FortnitePlayer.class);  
        
        player.username = username;
        
        System.debug('returning player: ' + player);
        
        return JSON.serialize(player);
    }

    global static FortnitePlayer lookupPlayerByUsername(String username) {
        
        String url = 'https://fortniteapi.io/lookup?username=' + username;
        
        HttpRequest request = new HttpRequest();        
        Http http = new Http();
        request.setEndpoint(url);
        request.setMethod('GET');
        request.setHeader('Authorization', FortniteApiKey);
        
        HTTPResponse response = http.send(request);
        
        System.debug('response.body: ' + response.getBody());
        
        FortnitePlayer player = (FortnitePlayer) JSON.deserialize(response.getBody(), FortnitePlayer.class);  
        
        player.username = username;
        
        System.debug('returning player: ' + player);
        
        return player;
    }


    @AuraEnabled
    global static String getRecentMatches(String username) {
        
        FortnitePlayer player = lookupPlayerByUsername(username);
        
        String url = 'https://fortniteapi.io/matches?account=' + player.account_id;
        
        HttpRequest request = new HttpRequest();        
        Http http = new Http();
        request.setEndpoint(url);
        request.setMethod('GET');
        request.setHeader('Authorization', FortniteApiKey);
        
        HTTPResponse response = http.send(request);
        
        System.debug('response.body: ' + response.getBody());
/*        
        FortnitePlayer player = (FortnitePlayer) JSON.deserialize(response.getBody(), FortnitePlayer.class);  
        
        player.username = username;
        
        System.debug('returning player: ' + player);
        
        return JSON.serialize(player);
*/        
        return response.getBody();
    }
    
}