force-app/main/default/objects/TemplateConfig__c/TemplateConfig__c.object-meta.xml
<CustomObject>
    <label>TemplateConfig</label>
    <nameField>
        <label>TemplateConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TemplateConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TemplateConfig__c/fields/Interview_ID__c.field-meta.xml
<CustomField>
    <fullName>Interview_ID__c</fullName>
    <label>Interview ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TemplateConfig__c/fields/Start_From__c.field-meta.xml
<CustomField>
    <fullName>Start_From__c</fullName>
    <label>Start From</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>blank</fullName>
                <default>true</default>
                <label>blank</label>
            </value>
            <value>
                <fullName>template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TemplateConfigController.cls
global with sharing class TemplateConfigController {

    @AuraEnabled
    global static TemplateConfig__c create(String name, String interviewId) {
        TemplateConfig__c config = new TemplateConfig__c();
        {
            config.Name = name;
            config.Interview_ID__c = interviewId;
        }
        upsert config;
        return [SELECT Id,Name,Start_From__c,Interview_ID__c FROM TemplateConfig__c WHERE Id =: config.Id];
    }

    @AuraEnabled
    global static List<TemplateConfig__c> listTemplateConfigs() {
        return [SELECT Id,Name,Start_From__c FROM TemplateConfig__c];
    }
    
    @AuraEnabled
    global static TemplateConfig__c getTemplateConfig(String id) {
        return [SELECT Id,Name,Start_From__c FROM TemplateConfig__c WHERE Id =: id];
    }
    
    @AuraEnabled
    global static void setStartFrom(String id, String val) {
        TemplateConfig__c config = [SELECT Id,Name,Start_From__c,Interview_ID__c FROM TemplateConfig__c WHERE Id =: id];
        config.Start_From__c = val;
        upsert config;
    }
}