force-app/main/default/objects/ApexStepList__c/ApexStepList__c.object-meta.xml
<CustomObject>
    <label>ApexStepList</label>
    <nameField>
        <label>ApexStepList Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ApexStepLists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApexStepList__c/fields/Items__c.field-meta.xml
<CustomField>
    <fullName>Items__c</fullName>
    <description>Comma-delimited list of items</description>
    <label>Items</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApexStepList__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Unique name for the list</description>
    <label>Name</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EinsteinAnalyticsEvent__e/EinsteinAnalyticsEvent__e.object-meta.xml
<CustomObject>
    <label>EinsteinAnalyticsEvent</label>
    <pluralLabel>EinsteinAnalyticsEvents</pluralLabel>
</CustomObject>

force-app/main/default/objects/EinsteinAnalyticsEvent__e/fields/payload__c.field-meta.xml
<CustomField>
    <fullName>payload__c</fullName>
    <description>The JSON payload to send to the target. For filters and selections this will be the standard EA format. For steps, refresh, etc., this will likely be specific to this POC. Refer to the source code for details and examples.</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EinsteinAnalyticsEvent__e/fields/target__c.field-meta.xml
<CustomField>
    <fullName>target__c</fullName>
    <description>One or more identifiers (IDs, names, etc.) to receive the event, comma separated.</description>
    <label>Target</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EinsteinAnalyticsEvent__e/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <description>The type of the event to allow the EA assets to respond accordingly.</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Token__c/Token__c.object-meta.xml
<CustomObject>
    <label>Token</label>
    <nameField>
        <label>Token Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Token__c/fields/ConsumerKey__c.field-meta.xml
<CustomField>
    <fullName>ConsumerKey__c</fullName>
    <label>ConsumerKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Token__c/fields/ConsumerSecret__c.field-meta.xml
<CustomField>
    <fullName>ConsumerSecret__c</fullName>
    <label>ConsumerSecret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Token__c/fields/Expires__c.field-meta.xml
<CustomField>
    <fullName>Expires__c</fullName>
    <inlineHelpText>Timestamp for token expiration</inlineHelpText>
    <label>Expires</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ApexTwitterUtils.cls
global with sharing class ApexTwitterUtils {

    @AuraEnabled
    global static String fireEvent(String type, String target, String payload) {

        EinsteinAnalyticsEvent__e event = new EinsteinAnalyticsEvent__e();
        event.type__c = type;
        event.target__c = target;
        event.payload__c = payload;
        
        EventBus.publish(event);
        
        String ret = 'foo';
        return ret;    
    }
    
    global static String getBearerToken(Boolean refresh) {
    
        Token__c token = [SELECT Id,Name,ConsumerKey__c,ConsumerSecret__c,TokenType__c,AccessToken__c,RefreshToken__c,Expires__c FROM Token__c WHERE Name = 'Twitter'];
        
        if (token.AccessToken__c != null && refresh != true) {
            return token.AccessToken__c;
        } else {
            
            String authString = token.ConsumerKey__c + ':' + token.ConsumerSecret__c;
    
            Blob authBlob = Blob.valueOf(authString);
            
            String auth = EncodingUtil.base64Encode(authBlob);
            
            String url = 'https://api.twitter.com/oauth2/token';
            
            HttpRequest request = new HttpRequest();        
            Http http = new Http();
            request.setEndpoint(url);
            request.setMethod('POST');
            request.setHeader('Content-type', 'application/x-www-form-urlencoded;charset=UTF-8');
            request.setHeader('Authorization', 'Basic ' + auth);
            request.setBody('grant_type=client_credentials');
            
            HTTPResponse response = http.send(request);
            
            String body = response.getBody();                    
    
            Map<String, Object> m = (Map<String, Object>) JSON.deserializeUntyped(body);
            
            String accessToken = (String) m.get('access_token');
                        
            token.AccessToken__c = accessToken;
            
            upsert token;
            
            return accessToken;
        }
    }
    
        
    // Map for looking up the Month by name from Twitter dates
    global static Map<String, Integer> MonthMap = new Map<String, Integer>{
        'Jan'=>1,'Feb'=>2,'Mar'=>3,'Apr'=>4,'May'=>5,'Jun'=>6,'Jul'=>7,'Aug'=>8,'Sep'=>9,'Oct'=>10,'Nov'=>11,'Dec'=>12
    };
    
    @AuraEnabled
    global static String getAppRateLimit(String resources) {
    
        if (resources == null) {
            resources = 'statuses';
        }
        
        String url = 'https://api.twitter.com/1.1/application/rate_limit_status.json?resources=' + resources;

        System.debug('------------------------------------------------------> url: ' + url);
            
        String accessToken = ApexTwitterUtils.getBearerToken(false);
    
        HttpRequest request = new HttpRequest();        
        Http http = new Http();
        request.setEndpoint(url);
        request.setMethod('GET');
        request.setHeader('Content-type', 'application/json');
        request.setHeader('Authorization', 'Bearer ' + accessToken);
        
        HTTPResponse response = http.send(request);

        String body = response.getBody();                    
        
        return body;
    
    }
    
    @AuraEnabled
    global static void updateApexStepList(String name, List<String> items) {
    
        ApexStepList__c l = null;
        String itemString = String.join(items, ',');
        
        try {
            l = [SELECT Id, Name__c, Items__c FROM ApexStepList__c WHERE Name__c =: name];
        } catch (Exception e) {
            l = new ApexStepList__c();
            l.Name__c = name;
        }
        
        l.Items__c = itemString;
        
        UPSERT l;
    }

    @AuraEnabled
    global static void deleteApexStepList(String name, List<String> items) {
    
        ApexStepList__c l = null;
        String itemString = String.join(items, ',');
        
        try {
            l = [SELECT Id, Name__c, Items__c FROM ApexStepList__c WHERE Name__c =: name];
            DELETE l;
        } catch (Exception e) {
        }
    }
    
    @AuraEnabled
    global static List<String> listApexStepLists() {
        List<ApexStepList__c> items = [SELECT Id, Name__c FROM ApexStepList__c];
        List<String> l = new List<String>();
        for (ApexStepList__c item : items) {
            l.add(item.Name__c);
        }
        
        return l;
    }

    @AuraEnabled
    global static List<String> getApexStepListItems(String name) {
        List<String> items = new List<String>();
        try {
            ApexStepList__c l = [SELECT Id, Name__c, Items__c FROM ApexStepList__c WHERE Name__c =: name];
            items = l.Items__c.split(',');
        } catch (Exception e) {
        }
        return items;
    }
        

    @AuraEnabled
    global static ApexStepList__c getApexStepList(String name) {
        ApexStepList__c l = [SELECT Id, Name__c, Items__c FROM ApexStepList__c WHERE Name__c =: name];
        
        return l;
    }
        
}