force-app/main/default/objects/VoiceMap__c/VoiceMap__c.object-meta.xml
<CustomObject>
    <description>Maps device, user, speaker, etc. Ids to SFDC</description>
    <label>Voice Map</label>
    <nameField>
        <label>VoiceMap Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voice Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VoiceMap__c/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <description>The name to display for the mapping</description>
    <label>Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceMap__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Detailed description of the device, service, etc.</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceMap__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>User_Id, Device_Id, Speaker_Id, etc.</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceMap__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <description>The SFDC User Id associated with the remote Id</description>
    <label>User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceMap__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The remote Id value</description>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceMap__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <description>The name of the device/service vendor</description>
    <label>Vendor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceTransaction__c/VoiceTransaction__c.object-meta.xml
<CustomObject>
    <label>Voice Transaction</label>
    <nameField>
        <displayFormat>VTX-{000000}</displayFormat>
        <label>VoiceRequest Index</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voice Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VoiceTransaction__c/fields/Application_Alias__c.field-meta.xml
<CustomField>
    <fullName>Application_Alias__c</fullName>
    <description>Name to display for the Application Id field</description>
    <label>Application Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceTransaction__c/fields/Application_Id__c.field-meta.xml
<CustomField>
    <fullName>Application_Id__c</fullName>
    <label>Application Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceTransaction__c/fields/Audio__c.field-meta.xml
<CustomField>
    <fullName>Audio__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Device supports the audio player interface</description>
    <label>Audio</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VoiceTransaction__c/fields/Device_Alias__c.field-meta.xml
<CustomField>
    <fullName>Device_Alias__c</fullName>
    <description>Name to display for Device Id field</description>
    <label>Device Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceTransaction__c/fields/Device_Id__c.field-meta.xml
<CustomField>
    <fullName>Device_Id__c</fullName>
    <description>The Id of the device</description>
    <label>Device Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceTransaction__c/fields/Display__c.field-meta.xml
<CustomField>
    <fullName>Display__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Device supports the display interface</description>
    <label>Display</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VoiceTransaction__c/fields/HTTP_Method__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Method__c</fullName>
    <label>HTTP Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceTransaction__c/fields/Intent_Name__c.field-meta.xml
<CustomField>
    <fullName>Intent_Name__c</fullName>
    <description>Name of the intent for the transaction</description>
    <label>Intent Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceTransaction__c/fields/Proxied_URL__c.field-meta.xml
<CustomField>
    <fullName>Proxied_URL__c</fullName>
    <description>The actual URL being called by the proxy</description>
    <label>Proxied URL</label>
    <length>4096</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VoiceTransaction__c/fields/Remote_Address__c.field-meta.xml
<CustomField>
    <fullName>Remote_Address__c</fullName>
    <description>The IP address of the device</description>
    <label>Remote Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceTransaction__c/fields/Request_URL__c.field-meta.xml
<CustomField>
    <fullName>Request_URL__c</fullName>
    <label>Request URL</label>
    <length>4096</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VoiceTransaction__c/fields/Slot_Values__c.field-meta.xml
<CustomField>
    <fullName>Slot_Values__c</fullName>
    <description>The key=value pairs for slots</description>
    <label>Slot Values</label>
    <length>8192</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VoiceTransaction__c/fields/Speaker_Alias__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Alias__c</fullName>
    <description>Name to display for Speaker Id field</description>
    <label>Speaker Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceTransaction__c/fields/Speaker_Confidence__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Confidence__c</fullName>
    <description>The confidence level for the speaker Id</description>
    <label>Speaker Confidence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VoiceTransaction__c/fields/Speaker_Id__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Id__c</fullName>
    <description>The remote speaker Id</description>
    <label>Speaker Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceTransaction__c/fields/URI__c.field-meta.xml
<CustomField>
    <fullName>URI__c</fullName>
    <description>The URI that is being proxied</description>
    <label>URI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceTransaction__c/fields/User_Alias__c.field-meta.xml
<CustomField>
    <fullName>User_Alias__c</fullName>
    <description>User name to display for User_Id field</description>
    <label>User Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceTransaction__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <description>The remote user Id</description>
    <label>User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceTransaction__c/fields/Video__c.field-meta.xml
<CustomField>
    <fullName>Video__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Device supports video</description>
    <label>Video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AlexaProxy.cls
@RestResource(urlMapping='/alexaproxy') 
global with sharing class AlexaProxy {

    @HttpGet
    global static void doGet() {        
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        /*
        System.debug('baseUrl: ' + URL.getSalesforceBaseUrl());
        System.debug('hostname: ' + URL.getSalesforceBaseUrl().getHost());
        System.debug('path: ' + URL.getSalesforceBaseUrl().getPath());
        System.debug('port: ' + URL.getSalesforceBaseUrl().getPort());
        System.debug('protocol: ' + URL.getSalesforceBaseUrl().getProtocol());
        System.debug('query: ' + URL.getSalesforceBaseUrl().getQuery());
        System.debug('ref: ' + URL.getSalesforceBaseUrl().getRef());
        System.debug('externalForm: ' + URL.getSalesforceBaseUrl().toExternalForm());
        
        System.debug('requestUrl: ' + URL.getCurrentRequestUrl());
        System.debug('httpMethod: ' + req.httpMethod);        
        System.debug('resourcePath: ' + req.resourcePath);        
        System.debug('requestURI: ' + req.requestURI);
        System.debug('remoteAddress: ' + req.remoteAddress);
        */
        
        Map<String, String> params = req.params;
        String uri = params.get('proxy_uri');
        
        uri = uri.replace('%3F', '?');

        System.debug('uri: ' + uri);
                 
        String theUrl = URL.getSalesforceBaseUrl().toExternalForm() + uri;
        
        System.debug('theUrl: ' + theUrl);
        
        String delim = '?';
        for (String param: req.params.keySet()) {
            if (param != 'proxy_uri') {
                theUrl += delim + param + '=' + req.params.get(param);
                delim = '&';
            }
        }

        System.debug('theUrl: ' + theUrl);
        
        HttpRequest request = new HttpRequest();        
        Http http = new Http();
        request.setEndpoint(theUrl);
        request.setMethod('GET');
        for (String name: req.headers.keySet()) {
            System.debug('header: ' + name + ' = ' + req.headers.get(name));
            if (name.contains('X-Salesforce') != true) {
                request.setHeader(name, req.headers.get(name));
            }
        }
        
        request.setHeader('Content-type', 'application/json');
        request.setHeader('Authorization', 'Bearer ' + UserInfo.getSessionId()); //accessToken);
        
        HTTPResponse response = http.send(request);
        
        System.debug('response body: ' + response.getBody());
        
        String body = JSON.serialize(response.getBody());
        
        RestContext.response.addHeader('Content-Type', 'application/json');
        RestContext.response.responseBody = Blob.valueOf(response.getBody()); //body);        


        // Need to add the response details!!! 
        System.debug('Calling LogTransaction');
        LogTransaction(req, res);
        
 
    }
    
    global static void LogTransaction(RestRequest req, RestResponse res) {
    
        System.debug('LogTransaction called');
        Map<String, String> params = req.params;
        String uri = params.get('proxy_uri');
        
        String theUrl = URL.getSalesforceBaseUrl().toExternalForm() + uri;
    
        String delim = '?';
        for (String param: req.params.keySet()) {
            if (param != 'proxy_uri') {
                theUrl += delim + param + '=' + req.params.get(param);
                delim = '&';
            }
        }    
    
        VoiceTransaction__c vtx = new VoiceTransaction__c(
            Request_URL__c = URL.getCurrentRequestUrl().toExternalForm(),
            HTTP_Method__c = req.httpMethod,
            Remote_Address__c = req.remoteAddress,
            URI__c = uri,
            Proxied_Url__c = theUrl
        );
             
        System.debug('vtx: ' + vtx);
        
        String value = null;
        
        for (String name: req.headers.keySet()) {
            value = req.headers.get(name);
            System.debug('header: ' + name + ' = ' +value);
            if (name.equals('Amazon-Speaker-Id')) {
                vtx.Speaker_Id__c = value;
            } else if (name.equals('Amazon-Speaker-Confidence')) {
                vtx.Speaker_Confidence__c = Decimal.valueOf(value);
            } else if (name.equals('Amazon-Device-Id')) {
                vtx.Device_Id__c = value;
            } else if (name.equals('Amazon-User-Id')) {
                vtx.User_Id__c = value;
            } else if (name.equals('Amazon-Application-Id')) {
                vtx.Application_Id__c = value;
            } else if (name.equals('Amazon-Device-AudioPlayer')) {
                vtx.Audio__c = true;
            } else if (name.equals('Amazon-Device-Display')) {
                vtx.Display__c = true;
            } else if (name.equals('Amazon-Device-VideoApp')) {
                vtx.Video__c = true;
            } else if (name.equals('Amazon-Intent-Name')) {
                vtx.Intent_Name__c = value;
            } else if (name.equals('Amazon-Intent-Slots')) {
                vtx.Slot_Values__c = value;
            }
                
        }

        // Move mapping to logging step!!!!!
        List<VoiceMap__c> mapList = [SELECT Id,Name,Type__c,Value__c,User_Id__c,Vendor__c,Description__c,Alias__c FROM VoiceMap__c];
        Map<String, VoiceMap__c> mapping = new Map<String, VoiceMap__c>();
        for (VoiceMap__c item : mapList) {
            mapping.put(item.Value__c, item);
        }
        
        VoiceMap__c item = null;
        Boolean dirty = false;
        item = mapping.get(vtx.Application_Id__c);
        if (item != null) {
            vtx.Application_Alias__c = item.Alias__c;
        }                
        item = mapping.get(vtx.Device_Id__c);
        if (item != null) {
            vtx.Device_Alias__c = item.Alias__c;
        }                
        item = mapping.get(vtx.User_Id__c);
        if (item != null) {
            vtx.User_Alias__c = item.Alias__c;
        }                
        item = mapping.get(vtx.Speaker_Id__c);
        if (item != null) {
            vtx.Speaker_Alias__c = item.Alias__c;
        }                

        System.debug('vtx: ' + vtx);
        
        UPSERT vtx;
    
    }
    
    @AuraEnabled
    public static List<VoiceTransaction__c> getVoiceTransactions() {
        List<VoiceTransaction__c> transactions  = [SELECT Id,Name,Request_URL__c,HTTP_Method__c,Remote_Address__c,URI__c,Proxied_Url__c,Device_Id__c,Application_Id__c,User_Id__c,Speaker_Id__c,Speaker_Confidence__c,Device_Alias__c,Application_Alias__c,User_Alias__c,Speaker_Alias__c,Audio__c,Video__c,Display__c,Intent_Name__c,Slot_Values__c,LastModifiedBy.Id,LastModifiedBy.Username,LastModifiedDate,CreatedDate FROM VoiceTransaction__c ORDER BY CreatedDate DESC];        
        return transactions;        
    }
    
}