force-app/main/default/objects/EinsteinAnalyticsEvent__e/EinsteinAnalyticsEvent__e.object-meta.xml
<CustomObject>
    <label>EinsteinAnalyticsEvent</label>
    <pluralLabel>EinsteinAnalyticsEvents</pluralLabel>
</CustomObject>

force-app/main/default/objects/EinsteinAnalyticsEvent__e/fields/payload__c.field-meta.xml
<CustomField>
    <fullName>payload__c</fullName>
    <description>The JSON payload to send to the target. For filters and selections this will be the standard EA format. For steps, refresh, etc., this will likely be specific to this POC. Refer to the source code for details and examples.</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EinsteinAnalyticsEvent__e/fields/target__c.field-meta.xml
<CustomField>
    <fullName>target__c</fullName>
    <description>One or more identifiers (IDs, names, etc.) to receive the event, comma separated.</description>
    <label>Target</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EinsteinAnalyticsEvent__e/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <description>The type of the event to allow the EA assets to respond accordingly.</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mock__c/Mock__c.object-meta.xml
<CustomObject>
    <label>Mock</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mock__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ApexMockController.cls
@RestResource(urlMapping='/apexmock/*') 
global with sharing class ApexMockController {
     
    // Wrapper classes
    global class MockObj {
        public String name;
        public String body;
        
        public MockObj(String n, String b) {
            this.name = n;
            this.body = b;
        }
        
        public MockObj(Mock__c mock) {
            this.name = mock.Name;
            this.body = mock.Body__c;
        }
    }

    @HttpPost            
    global static String doPost(String name, String dummy) {
        Mock__c mock = null;
        String body = null;
        
        try {
            mock = [SELECT Id, Name, Body__c FROM Mock__c WHERE name =: name];
            body = mock.Body__c;
        } catch (Exception e) {
        }
                
        return body;
    }

    global static MockObj updateMock(String name, String body) {
        Mock__c mock = null;
        
        try {
            mock = [SELECT Id, Name, Body__c FROM Mock__c WHERE name =: name];
        } catch (Exception e) {
            mock = new Mock__c();
            mock.Name = name;        
        }
        
        mock.Body__c = body;
        
       
        UPSERT mock;
        
        
        
        /* FOR TESTING ONLY */
        EinsteinAnalyticsEvent__e event = new EinsteinAnalyticsEvent__e();
        event.type__c = 'refresh';
        event.target__c = '0FKB000000092VyOAI';
        event.payload__c = null;
        
        EventBus.publish(event);
        
               
        
        
        return new MockObj(name, body);
    }

    @HttpPut           
    global static String doPut() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String name = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);

        MockObj mock = null;
        
        if (name != 'apexmock') {
            String body = req.requestBody.toString();
            mock = updateMock(name, body);
        }
        return JSON.serialize(mock);
    }

    @AuraEnabled
    global static String putMock(String name, String body) {
        MockObj mock = updateMock(name, body);
        return JSON.serialize(mock);
    }
            
    global static Map<String, MockObj> getMocks(String name) {
        Map<String, MockObj> mockObjs = new Map<String, MockObj>();
        if (name != null && name != 'apexmock') {
            Mock__c mock = [SELECT Id, Name, Body__c FROM Mock__c WHERE name =: name];
            mockObjs.put(mock.Name, new MockObj(mock.Name, mock.Body__c));
        } else {
            List<Mock__c> mocks = [SELECT Id, Name, Body__c FROM Mock__c ORDER BY Name];
            for (Mock__c mock : mocks) {
                mockObjs.put(mock.Name, new MockObj(mock.Name, mock.Body__c));
            }
        }
        
        return mockObjs;
    }

    @HttpGet
    global static Map<String, MockObj> doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String name = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);
        return getMocks(name);
    }

    @AuraEnabled
    global static String listMocks(String name) {
        Map<String, MockObj> mocks = getMocks(name);
        return JSON.serialize(mocks);
    }
    
    @HttpDelete
    global static String doDelete() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String name = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);
        String msg = null;
        if (name != 'apexmock') {
            try {
                Mock__c mock = [SELECT Id, Name, Body__c FROM Mock__c WHERE name =: name];
                DELETE mock;
                msg = 'Successfully deleted ' + mock.Name;
            } catch (Exception e) {
                msg = 'Exception: ' + e.getMessage();            
            }
        } else {
            msg = 'DELETE not applicable to list endpoint';
        }
        
        return '{"msg": "' + msg + '"}';
    }
    
}