force-app/main/default/objects/EinsteinAnalyticsEvent__e/EinsteinAnalyticsEvent__e.object-meta.xml
<CustomObject>
    <label>EinsteinAnalyticsEvent</label>
    <pluralLabel>EinsteinAnalyticsEvents</pluralLabel>
</CustomObject>

force-app/main/default/objects/EinsteinAnalyticsEvent__e/fields/payload__c.field-meta.xml
<CustomField>
    <fullName>payload__c</fullName>
    <description>The JSON payload to send to the target. For filters and selections this will be the standard EA format. For steps, refresh, etc., this will likely be specific to this POC. Refer to the source code for details and examples.</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EinsteinAnalyticsEvent__e/fields/target__c.field-meta.xml
<CustomField>
    <fullName>target__c</fullName>
    <description>One or more identifiers (IDs, names, etc.) to receive the event, comma separated.</description>
    <label>Target</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EinsteinAnalyticsEvent__e/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <description>The type of the event to allow the EA assets to respond accordingly.</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/eaPlatformEventController.cls
@RestResource(urlMapping='/ea/platformevents/*') 
global with sharing class eaPlatformEventController {

/*               
    global static String doPost(String type, String target, String payload) {
    
        String ret = 'foo';
        return ret;    
    }
*/    
    @HttpPost        
    @AuraEnabled
    global static String fireEvent(String type, String target, String payload) {

        EinsteinAnalyticsEvent__e event = new EinsteinAnalyticsEvent__e();
        event.type__c = type;
        event.target__c = target;
        event.payload__c = payload;
        
        EventBus.publish(event);
        
        String ret = 'foo';
        return ret;    
    }
    
}